In [1]:
import pandas as pd
import numpy as np

frame = pd.DataFrame(np.random.randn(4,3),
             columns=list('bde'),
             index=['台北','台中','台南','高雄'])
frame

           b         d         e
台北 -0.992747  0.672040  0.810017
台中  1.914791  1.731453  0.849115
台南  0.126666  0.799426 -1.660351
高雄 -1.034022  0.119720 -0.872464

In [2]:
def formap(value):
    return f'{value:.3f}%'

frame.map(formap)

          b       d        e
台北  -0.993%  0.672%   0.810%
台中   1.915%  1.731%   0.849%
台南   0.127%  0.799%  -1.660%
高雄  -1.034%  0.120%  -0.872%

In [3]:
import numpy as np
import pandas as pd

scores = np.random.randint(50,101,size=(50,5))
scores_pd = pd.DataFrame(scores,columns=['國文', '英文', '數學', '地理', '歷史'],index=range(1,51))
scores_pd.index.name="學號"
scores_pd.columns.name="科目"
scores_pd

科目   國文   英文   數學   地理  歷史
學號
1    91   88   79   64  62
2    64   75   80   73  99
3    94   57   98   77  50
4    88   50   93   56  92
5    73   98   59   52  73
6   100   56   66   77  52
7   100   58  100   94  76
8    99   75   93   84  61
9    63   53   79   64  58
10   80   81   60   90  92
11   78   91   91   75  85
12   96   99   61   72  52
13   61   63   54   88  55
14   82   76   62   86  76
15   94   91   56   51  79
16   76   64   61   58  81
17   50   74   58   95  60
18   95   55   75   51  97
19   76   85   81   86  53
20   63  100   60   70  65
21   64   74   84   72  95
22   74   98   83   86  95
23   65   99   88   54  99
24   55   84   58   77  80
25   51   68   50   92  94
26   51   74   79   53  50
27   63   79   94   59  84
28   50   63   88   59  91
29   55   58   91   72  62
30   93   63   97   73  53
31   50   90   55   80  52
32   78   96   88   54  69
33   85   50   50   56  71
34   99   99   50   58  87
35   50   92   84   60  64
36   86   62   74   93  79
37   75   50   90   53  57
38   79   62   85   88  60
39   94   70   54   76  60
40   91   83   63   70  55
41   92   56   64   86  57
42   97   82   74   80  70
43   51   94   92   55  76
44   81   80   60   67  55
45   90   82   69   57  79
46   85   87   86   85  74
47   74   76   94   58  88
48   52   81   72  100  92
49   67   62   79   87  99
50   80   72   67   91  93

In [4]:
def call(s):
    min = s.min()
    max = s.max()
    median = s.median()
    return pd.Series([min,max,median],index=['最低分','最高分','中間值'])

scores_pd.apply(call)

科目      國文     英文     數學     地理    歷史
最低分   50.0   50.0   50.0   51.0  50.0
最高分  100.0  100.0  100.0  100.0  99.0
中間值   78.0   75.5   77.0   72.5  73.5

In [5]:
def call1(s):
    less60 = s[s<60]
    return less60.count()

less60_s= scores_pd.apply(call1,axis=1)
scores_pd['不及格的科目'] = less60_s
scores_pd

科目   國文   英文   數學   地理  歷史  不及格的科目
學號
1    91   88   79   64  62       0
2    64   75   80   73  99       0
3    94   57   98   77  50       2
4    88   50   93   56  92       2
5    73   98   59   52  73       2
6   100   56   66   77  52       2
7   100   58  100   94  76       1
8    99   75   93   84  61       0
9    63   53   79   64  58       2
10   80   81   60   90  92       0
11   78   91   91   75  85       0
12   96   99   61   72  52       1
13   61   63   54   88  55       2
14   82   76   62   86  76       0
15   94   91   56   51  79       2
16   76   64   61   58  81       1
17   50   74   58   95  60       2
18   95   55   75   51  97       2
19   76   85   81   86  53       1
20   63  100   60   70  65       0
21   64   74   84   72  95       0
22   74   98   83   86  95       0
23   65   99   88   54  99       1
24   55   84   58   77  80       2
25   51   68   50   92  94       2
26   51   74   79   53  50       3
27   63   79   94   59  84       1
28   50   63   88   59  91       2
29   55   58   91   72  62       2
30   93   63   97   73  53       1
31   50   90   55   80  52       3
32   78   96   88   54  69       1
33   85   50   50   56  71       3
34   99   99   50   58  87       2
35   50   92   84   60  64       1
36   86   62   74   93  79       0
37   75   50   90   53  57       3
38   79   62   85   88  60       0
39   94   70   54   76  60       1
40   91   83   63   70  55       1
41   92   56   64   86  57       2
42   97   82   74   80  70       0
43   51   94   92   55  76       2
44   81   80   60   67  55       1
45   90   82   69   57  79       1
46   85   87   86   85  74       0
47   74   76   94   58  88       1
48   52   81   72  100  92       1
49   67   62   79   87  99       0
50   80   72   67   91  93       0